package com.ssafy.backend.domain.analyze;

public enum Word {
    ADULT, ARTS_ENTERTAINMENT, AUTOS_VEHICLES, BEAUTY_FITNESS, BOOKS_LITERATURE, BUSINESS_INDUSTRIAL, COMPUTERS_ELECTRONICS,
    FINANCE, FOOD_DRINK, GAMES, HEALTH, HOBBIES_LEISURE, HOME_GARDEN, INTERNET_TELECOM, JOBS_EDUCATION, LAW_GOVERNMENT,
    NEWS, ONLINE_COMMUNITIES, PEOPLE_SOCIETY, PETS_ANIMALS, REAL_ESTATE, REFERENCE, SCIENCE, SENSITIVE_SUBJECTS, SHOPPING,
    SPORTS, TRAVEL_TRANSPORTATION
}
